// IMPORTANT do not edit this file unless you know what you are doing.
// Tests should be defined in requirejs modules. See 'test.unit.js' for example.

// load all test files ending in 'unit.js' with require.js (see next block)
var tests = [];
for (var file in window.__karma__.files) {
	if (window.__karma__.files.hasOwnProperty(file)) {
		if (/unit\.js$/.test(file)) {
			tests.push(file);
		}
	}
}

requirejs.config({
	// Karma serves files from '/base'
	baseUrl: 'base/app',
	paths: {
		"libs": "../libs"
	},

	// ask require.js to load all previously specified test files on start.
	deps: tests,
	callback: window.__karma__.start
});